---
# tasks file for lighttpd
- name:  Atualizar pacotes
  apt:
    update_cache: yes

- name: Instalar lighttpd
  apt:
    name: lighttpd
    state: present

- name: Iniciar serviço lighttpd
  service:
    name: lighttpd
    state: started
    enabled: yes

- name: Cria meu diretorio web
  file:
    path: "{{ default_dir }}"
    state: directory
