---
# tasks file for lighttpd
- name:  Atualizar pacotes
  apt:
    update_cache: yes

- name: Instalar lighttpd
  apt:
    name: lighttpd
    state: present

- name: Iniciar serviço lighttpd
  service:
    name: lighttpd
    state: started
    enabled: yes

- name: Verificando o status do lighttpd
  command: "systemctl status lighttpd"
  register: status_lighttpd

- name: Exibindo o register
  debug:
    msg: "{{ status_lighttpd.stdout }}"

- name: Cria meu diretorio web
  file:
    path: "{{ default_dir }}/meu_diretorio_web"
    state: directory
    owner: gerencia
    group: gerencia
    modification_time: preserve
    access_time: preserve 
 
- name: Copiar index.html para meu_diretorio_web
  copy:
    src: "{{ default_dir }}/index.html"
    dest: "{{ default_dir }}/meu_diretorio_web"
    owner: gerencia
    group: gerencia

- name: Copiar o arquivo de configuração lighttpd
  template:
    src: templates/lighttpd.conf
    dest: /etc/lighttpd/lighttpd.conf
  notify: Reiniciar lighttpd
